services:
  api:
    build: ./web/api
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    volumes:
      - ./api_data:/app/data
    restart: always

  client:
    build: 
      context: ./web/client
      args:
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "80:80"
    depends_on:
      - api
    restart: always
